### ISSUE TITLE
Is trained model on cityScapes avaliable？

### ISSUE THREAD

**Issue by Wanger-SJTU** [wctu/SEAL#10]

**Comment by xwasco** [comment]
Hello @wctu, am interested too, thanks

**Comment by SteveJunGao** [comment]
I'm also interested in the model trained on the Cityscapes, too, could you provide it? Thanks!

**Comment by wctu** [comment]
Hi all,

The model is included in /test.

**Comment by SteveJunGao** [comment]
Many thanks!!
